name: Unit tests

on:
  push:
    branches: 
    - '*'
  pull_request:
    branches:
    - '*'

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        config: [
            all
          ]
          
    container:       
      image: px4io/px4-dev-nuttx-focal:2021-09-08
      options: --privileged --ulimit core=-1 --security-opt seccomp=unconfined
    steps:
    - uses: actions/checkout@v3
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        submodules: 'true'
      
    - name: make ${{matrix.config}}
      run: make ${{matrix.config}}

    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v3
      with:
        gcov: true
