name: "ECLAIR push"
on: [workflow_dispatch, push]
env:
  GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
jobs:
  Analyze:
    runs-on: eclairit
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3
      with:
        submodules: 'true'
    - name: Build and analyze with ECLAIR
      run: |
        set -eu
        ./prepare.sh Debug
        cd ECLAIR
        ./analyze.sh
    - name: ECLAIR analysis log
      if: always()
      run: cat ECLAIR_out/ANALYSIS.log
    - name: ECLAIR report log
      if: always()
      run: cat ECLAIR_out/REPORT.log
    - name: Upload ECLAIR artifacts
      if: always()
      uses: actions/upload-artifact@v3
      with:
        name: artifacts
        path: ECLAIR_out
    - name: Upload ECLAIR SARIF
      uses: BUGSENG/codeql-action/upload-sarif@v2
      with:
        sarif_file: ECLAIR_out/reports.sarif
    - name: Publish ECLAIR results
      env:
        WTOKEN: ${{secrets.WTOKEN}}
      run: ECLAIR/action_push.sh "${WTOKEN}" ECLAIR_out
