name: "ECLAIR pull request"
on:
  pull_request_target:
    types: ['opened', 'synchronize']
env:
  GITHUB_EVENT_PULL_REQUEST_NUMBER: ${{github.event.pull_request.number}}
  GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
jobs:
  Analyze:
    runs-on: eclairit
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3
      with:
        ref: "refs/pull/${{github.event.pull_request.number}}/merge"
        submodules: 'true'
    - name: Build and analyze with ECLAIR
      run: |
        set -eu
        ./prepare.sh Debug
        ECLAIR/analyze.sh
    - name: ECLAIR analysis log
      if: always()
      run: cat ECLAIR_out/ANALYSIS.log
    - name: ECLAIR report log
      if: always()
      run: cat ECLAIR_out/REPORT.log
    - name: Upload ECLAIR artifacts
      if: always()
      uses: actions/upload-artifact@v3
      with:
        name: artifacts
        path: ECLAIR_out
    - name: Upload ECLAIR SARIF
      uses: BUGSENG/codeql-action/upload-sarif@v2
      with:
        sarif_file: reports.sarif
    - name: Publish ECLAIR results
      env:
        PR_HEAD_REF: ${{github.event.pull_request.head.ref}}
        PR_HEAD_REPO: ${{github.event.pull_request.head.repo.name}}
        PR_BASE_REF: ${{github.event.pull_request.base.ref}}
        PR_USER: ${{github.event.pull_request.user.login}}
        WTOKEN: ${{secrets.WTOKEN}}
      run: ECLAIR/action_pull_request.sh "${WTOKEN}" ECLAIR_out
